"""empty message

Revision ID: b39882573f06
Revises: 
Create Date: 2022-03-03 19:38:53.190536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b39882573f06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Campaign',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.String(length=255), nullable=True),
    sa.Column('ad_strategy_id', sa.String(length=255), nullable=True),
    sa.Column('bid_strategy', sa.String(length=255), nullable=True),
    sa.Column('budget_remaining', sa.String(length=255), nullable=True),
    sa.Column('buying_type', sa.String(length=255), nullable=True),
    sa.Column('can_create_brand_lift_study', sa.String(length=255), nullable=True),
    sa.Column('can_use_spend_cap', sa.String(length=255), nullable=True),
    sa.Column('configured_status', sa.String(length=255), nullable=True),
    sa.Column('created_time', sa.String(length=255), nullable=True),
    sa.Column('daily_budget', sa.String(length=255), nullable=True),
    sa.Column('effective_status', sa.String(length=255), nullable=True),
    sa.Column('is_skadnetwork_attribution', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('objective', sa.String(length=255), nullable=True),
    sa.Column('pacing_type', sa.String(length=255), nullable=True),
    sa.Column('smart_promotion_type', sa.String(length=255), nullable=True),
    sa.Column('source_campaign_id', sa.String(length=255), nullable=True),
    sa.Column('special_ad_categories', sa.String(length=255), nullable=True),
    sa.Column('special_ad_category', sa.String(length=255), nullable=True),
    sa.Column('special_ad_category_country', sa.String(length=255), nullable=True),
    sa.Column('start_time', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('stop_time', sa.String(length=255), nullable=True),
    sa.Column('topline_id', sa.String(length=255), nullable=True),
    sa.Column('updated_time', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_reach', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('date', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date'),
    sa.UniqueConstraint('page_reach'),
    sa.UniqueConstraint('source')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('social_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fb_access_token', sa.String(length=500), nullable=True),
    sa.Column('fb_secret', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fb_access_token'),
    sa.UniqueConstraint('fb_secret')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('social_accounts')
    op.drop_table('users')
    op.drop_table('Results')
    op.drop_table('Campaign')
    # ### end Alembic commands ###
