from . import db

class Leads(db.Model):
        ad_id = 'ad_id'
        ad_name = 'ad_name'
        adset_id = 'adset_id'
        adset_name = 'adset_name'
        campaign_id = 'campaign_id'
        campaign_name = 'campaign_name'
        created_time = 'created_time'
        custom_disclaimer_responses = 'custom_disclaimer_responses'
        field_data = 'field_data'
        form_id = 'form_id'
        home_listing = 'home_listing'
        id = 'id'
        is_organic = 'is_organic'
        partner_name = 'partner_name'
        platform = 'platform'
        retailer_item_id = 'retailer_item_id'
        vehicle = 'vehicle'